import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const b64=(s:string)=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function decrypt(v:string){const[i,c]=v.split("."),d=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(Deno.env.get("GMAIL_CLIENT_SECRET")!)),k=await crypto.subtle.importKey("raw",d,"AES-GCM",false,["decrypt"]);return new TextDecoder().decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:b64(i)},k,b64(c)));}
const decode=(v:string)=>new TextDecoder().decode(b64(v.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(v.length/4)*4,"=")));
const head=(m:any,n:string)=>m.payload?.headers?.find((h:any)=>h.name.toLowerCase()===n)?.value??"";
const text=(p:any):string=>p?.body?.data?decode(p.body.data):(p?.parts??[]).map(text).join("\n");
const base64url=(v:string)=>btoa(unescape(encodeURIComponent(v))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
const address=(v:string)=>v.match(/<([^>]+)>/)?.[1]??v.trim();
Deno.serve(async(req)=>{if(req.method!=="POST")return new Response("Method not allowed",{status:405});
 const base=Deno.env.get("SUPABASE_URL")!,roleKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,auth=req.headers.get("authorization")??"",service=createClient(base,roleKey);
 if(auth!==`Bearer ${roleKey}`){const client=createClient(base,Deno.env.get("SUPABASE_ANON_KEY")!,{global:{headers:{Authorization:auth}}}),{data:{user}}=await client.auth.getUser();if(!user)return new Response("Unauthorized",{status:401});const{data:p}=await service.from("profiles").select("role").eq("id",user.id).single();if(p?.role!=="admin")return new Response("Forbidden",{status:403});}
 const{data:connections}=await service.from("gmail_connections").select("*").eq("enabled",true);let created=0,scanned=0,ignored=0;const errors:string[]=[];
 for(const connection of connections??[]){try{const refresh=await decrypt(connection.refresh_token_cipher),tr=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({client_id:Deno.env.get("GMAIL_CLIENT_ID")!,client_secret:Deno.env.get("GMAIL_CLIENT_SECRET")!,refresh_token:refresh,grant_type:"refresh_token"})}),tokens=await tr.json();if(!tr.ok)throw new Error("Google token refresh failed");
  const lr=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=40&q=in%3Ainbox%20newer_than%3A7d",{headers:{Authorization:`Bearer ${tokens.access_token}`}}),listed=await lr.json();if(!lr.ok)throw new Error(`Gmail inbox returned ${lr.status}`);const{data:done}=await service.from("gmail_processed_messages").select("message_id,outcome").eq("organisation_id",connection.organisation_id),seen=new Set((done??[]).filter((x:any)=>x.outcome==="task_created"||x.outcome==="task_and_draft_created"||x.outcome==="ignored").map((x:any)=>x.message_id)),pending=(listed.messages??[]).filter((item:any)=>!seen.has(item.id)).slice(0,8),{data:leads}=await service.from("leads").select("id,job_ref,name,email,address,job_type,stage").eq("organisation_id",connection.organisation_id),{data:profile}=await service.from("profiles").select("legacy_user_id,id").eq("id",connection.user_id).single(),owner=profile?.legacy_user_id??profile?.id;
  for(const item of pending){const mr=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${item.id}?format=full`,{headers:{Authorization:`Bearer ${tokens.access_token}`}}),m=await mr.json();if(!mr.ok){errors.push(`Message read returned ${mr.status}`);continue}scanned++;const email={from:head(m,"from"),subject:head(m,"subject"),date:head(m,"date"),body:text(m.payload).slice(0,6000)};
   const prompt=`Classify this incoming email for a UK roofing company. Important means a person must take a concrete action: customer reply, quote acceptance/change, urgent leak/complaint, survey/job scheduling, supplier or payment deadline. Ignore marketing, newsletters, spam, automated notices and receipts with no action. Match a CRM job only with clear evidence. For important genuine person-to-person emails, write a concise professional UK-English reply draft. Never promise a price, date, refund or completed work unless the email/CRM proves it; instead say the team will check and confirm. Do not draft replies to automated/no-reply senders. End drafts with "Kind regards,\nProLine Roofing & Solar". Return JSON only: {"important":boolean,"confidence":number,"title":string,"due_offset_days":number,"priority":"low"|"medium"|"high","reason":string,"lead_id":string|null,"create_draft":boolean,"draft_reply":string}. EMAIL=${JSON.stringify(email)} CRM=${JSON.stringify(leads??[])}`;
   const model=Deno.env.get("GEMINI_MODEL")??"gemini-3.6-flash",gr=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${Deno.env.get("GEMINI_API_KEY")}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.1,responseMimeType:"application/json"}})}),g=await gr.json();if(!gr.ok){errors.push(`Gemini ${gr.status}: ${String(g?.error?.message??"failed").slice(0,120)}`);continue}const raw=g.candidates?.[0]?.content?.parts?.[0]?.text;if(!raw){errors.push("Gemini returned no classification");continue}let result:any;try{result=JSON.parse(raw)}catch{errors.push("Gemini returned invalid JSON");continue}
   let taskId=null,outcome="ignored";if(result.important===true&&Number(result.confidence)>=.7&&String(result.title??"").trim()){taskId=crypto.randomUUID();const due=new Date();due.setUTCDate(due.getUTCDate()+Math.max(0,Math.min(14,Number(result.due_offset_days)||0)));const{error:taskError}=await service.from("general_tasks").insert({id:taskId,title:String(result.title).slice(0,180),completed:false,due_date:due.toISOString().slice(0,10),priority:["low","medium","high"].includes(result.priority)?result.priority:"medium",category:"Email",notes:`From: ${email.from}\nSubject: ${email.subject}\n${String(result.reason??"")}\nGmail message: ${item.id}`,created_at:new Date().toISOString().slice(0,10),assigned_to:[owner],organisation_id:connection.organisation_id});if(taskError){errors.push(`Task save failed: ${taskError.message}`);continue}outcome="task_created";created++;
    const recipient=address(head(m,"reply-to")||email.from),messageID=head(m,"message-id"),draft=String(result.draft_reply??"").trim();if(result.create_draft===true&&draft&&recipient&&!/no-?reply/i.test(recipient)){const subject=/^re:/i.test(email.subject)?email.subject:`Re: ${email.subject}`,raw=[`To: ${recipient}`,`Subject: ${subject}`,messageID?`In-Reply-To: ${messageID}`:"",messageID?`References: ${messageID}`:"","Content-Type: text/plain; charset=UTF-8","",draft].filter(Boolean).join("\r\n"),dr=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/drafts",{method:"POST",headers:{Authorization:`Bearer ${tokens.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({message:{threadId:m.threadId,raw:base64url(raw)}})});if(dr.ok)outcome="task_and_draft_created";else console.error("Gmail draft failed",await dr.text());}}
   else ignored++;await service.from("gmail_processed_messages").upsert({organisation_id:connection.organisation_id,message_id:item.id,outcome,task_id:taskId,processed_at:new Date().toISOString()},{onConflict:"organisation_id,message_id"});}
  await service.from("gmail_connections").update({last_scanned_at:new Date().toISOString()}).eq("id",connection.id);}catch(e){const message=e instanceof Error?e.message:String(e);errors.push(message);console.error("Gmail scan failed",connection.id,e)}}return new Response(JSON.stringify({ok:errors.length===0,connections:connections?.length??0,messages_scanned:scanned,tasks_created:created,messages_ignored:ignored,errors:errors.slice(0,8)}),{status:errors.length?207:200,headers:{"Content-Type":"application/json"}});});
