import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const bytesToB64=(v:Uint8Array)=>btoa(String.fromCharCode(...v));
async function encrypt(value:string){const material=new TextEncoder().encode(Deno.env.get("GMAIL_CLIENT_SECRET")!);const digest=await crypto.subtle.digest("SHA-256",material);const key=await crypto.subtle.importKey("raw",digest,"AES-GCM",false,["encrypt"]);const iv=crypto.getRandomValues(new Uint8Array(12));const encrypted=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,new TextEncoder().encode(value)));return `${bytesToB64(iv)}.${bytesToB64(encrypted)}`;}
Deno.serve(async(req)=>{const input=new URL(req.url),code=input.searchParams.get("code"),state=input.searchParams.get("state");if(!code||!state)return new Response("Gmail connection cancelled.",{status:400});
 const base=Deno.env.get("SUPABASE_URL")!,service=createClient(base,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);const{data:p}=await service.from("gmail_oauth_states").select("*").eq("state",state).gt("expires_at",new Date().toISOString()).maybeSingle();if(!p)return new Response("Connection link expired.",{status:400});
 const redirect=`${base}/functions/v1/gmail-oauth-callback`;const response=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({code,client_id:Deno.env.get("GMAIL_CLIENT_ID")!,client_secret:Deno.env.get("GMAIL_CLIENT_SECRET")!,redirect_uri:redirect,grant_type:"authorization_code"})});const tokens=await response.json();if(!response.ok||!tokens.refresh_token)return new Response("Google did not grant offline Gmail access. Try connecting again.",{status:400});
 const pr=await fetch("https://gmail.googleapis.com/gmail/v1/users/me/profile",{headers:{Authorization:`Bearer ${tokens.access_token}`}}),gmail=await pr.json();if(!pr.ok)return new Response("Gmail profile could not be read.",{status:400});
 await service.from("gmail_connections").upsert({organisation_id:p.organisation_id,user_id:p.user_id,gmail_address:gmail.emailAddress,refresh_token_cipher:await encrypt(tokens.refresh_token),enabled:true},{onConflict:"organisation_id,gmail_address"});await service.from("gmail_oauth_states").delete().eq("state",state);
 return new Response(`<html><body style="font-family:-apple-system;padding:40px"><h2>Gmail connected</h2><p>${gmail.emailAddress} is now connected to ProLine CRM. You can close this page.</p></body></html>`,{headers:{"Content-Type":"text/html"}});});
